#!/usr/bin/env bash
# This script installs Nginx and configures it to serve a "Hello World!" page.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Configure Nginx to listen on port 80
echo "server {
    listen 80;
    root /var/www/html;
    index index.nginx-debian.html; 
}" > /etc/nginx/sites-available/default

# Start the Nginx service
sudo service nginx start

# Allow incoming HTTP traffic on port 80 through the firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file with the contents "Hello World!"
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Enable the Nginx site
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
